<?php

define('SUCCESS_CODE', 0);
define('ERROR_METHOD_NOT_SUPPORTED', 1);

define('ERROR_ARG_PATTERN_NOT_PROVIDED', 2);
define('ERROR_ARG_FILE_NOT_PROVIDED', 4);
define('ERROR_FILE_NOT_FOUND', 8);

define('ERROR_FILE_UPLOAD_FAILED', 2);
define('ERROR_FILE_UPLOAD_NOT_ACCEPTED', 4);

?>